Update checkBuild.yml

diff --git a/.github/workflows/checkBuild.yml b/.github/workflows/checkBuild.yml
--- a/.github/workflows/checkBuild.yml
+++ b/.github/workflows/checkBuild.yml
@@ -28,7 +28,24 @@ jobs:
         node-version: ${{ matrix.node-version }}
         
     - run: npm ci
-    
-    - run: npm run build --if-present
-    
+    - run: npm run build
+    - run: npm run format:check
     - run: npm test
+    
+    - name: Check for uncommited changes
+      run: |
+        if [[ "$(git status --porcelain)" != "" ]]; then
+          echo ----------------------------------------
+          echo git status
+          echo ----------------------------------------
+          git status
+          echo ----------------------------------------
+          echo git diff
+          echo ----------------------------------------
+          git diff
+          echo ----------------------------------------
+          echo Troubleshooting
+          echo ----------------------------------------
+          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && mvn -B clean package -Pproduction"
+          exit 1
+        fi
